### PR TITLE
Adding README.md file

### PR DESCRIPTION
**Pull request by rkraja2751**

### CODE REVIEW

**Comment by rkraja2751** [comment]
Issue #1 : Readme file is added.

**Comment by dibyadas** [comment]
Hey @rkraja2751, could rebase the latest master and squash your commits into 1 commit? It will be cleaner. Also, good work on the README.

**Comment by rkraja2751** [comment]
ok. I will fix it.

**Comment by rkraja2751** [comment]
I will again add a new pull request in few minutes. Thanks for consideration.

**Pull request closed without merging**
